apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 3005
  type: NodePort
