apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  strategy:
    rollingUpdate: 
      maxSurge: 50% 
      maxUnavailable: 10%
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: bxr0820/apigateway:latest
        ports:
        - containerPort: 9092
        resources:
          requests:
            cpu: "50m"  # 请求的 CPU 资源
          limits:
            cpu: "1000m"  # CPU 使用的最大限制
