apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30005
  type: NodePort
